### ISSUE TITLE
Can't get auto splitter working. (TSH&R)

### ISSUE THREAD

**Issue by DontAnnoyMeDH** [zoton2/LiveSplit.Scripts#15]
Hey, I'm trying to get the auto splitter working on the Simpsons Hit & Run. I've tried it by activating the splitter through Live Split, and by downloading the ASL file and adding an Auto Splitter. In settings for both, it says "Game Version: NonENGVarious". I have a legitimate copy of the game, brought from the UK and I have also tried running Live Split as administrator. Please help.

**Comment by zoton2** [comment]
If the game version is showing, it's correctly identified your game, but I'd expect a UK copy to be an English version. I'd say you used the wrong EXE but if the game starts up you are probably using the right one.

I advise you come into our Discord if possible for more help, there's an invite link here: https://www.speedrun.com/shar/thread/bktv6

**Comment by DontAnnoyMeDH** [comment]
I've figured it out. I didn't have the no cd exe. Thanks though.
