### ISSUE TITLE
LiveSplit.GTAVC - restarting your game and loading a save resets/starts splits.

### ISSUE THREAD

**Issue by zoton2** [zoton2/LiveSplit.Scripts#2]
In regards to the GTAVC autosplitter:

If you have to reset your game or it crashes and then you load a save, the timer will reset and then the splits will start again.

This is because right now it relies on a memory address called "GameState", which is 8 (12 for JP) on initial loads into the game and for new games and 9 (13 for JP) in game. This works for new game at any time but unfortunately happens when loading a game from a fresh start too. It does not happen when loading a game after you have started the game (either via new game or loading a save) though.

**Comment by pitpo** [comment]
```
; Addresses used to check for closing the game or crashing or loading a save
if VersionOffset = -4088 ; Steam version
{
	StartingNewGameCheckAddress := 0x0068667C
	LoadingGameCheckAddress := 0x00695662	
	LoadingFromFreshStartUpAddress := 0x006DCDC0
}
else 
{
	StartingNewGameCheckAddress := 0x0068767C
	LoadingGameCheckAddress := 0x0069665A
	if VersionOffset = 8 ; Version 1.1
		LoadingFromFreshStartUpAddress := 0x006DDE18
	else
		LoadingFromFreshStartUpAddress := 0x006DDE28	
}
```

I'm pretty sure you were playing with these addresses and this didn't work. The question is, were you only messing around jp version? Offsets are clearly very different from the "standard" ones, but maybe it's possible to find them (for jp version) based on hex values in these regions of 1.0/1.1/steam versions. If they didn't work for remaining versions, maybe you forgot to apply -0x400000 offset on Lighnat0r's values.

**Comment by Lighnat0r** [comment]
I actually got japanese versions of those addresses, just don't remember if I actually checked them to be correct or estimated based on the general offset.

```AutoHotkey
; Addresses used to check for closing the game or crashing or loading a save
if VersionOffset = -4088 ; Steam version
{
	StartingNewGameCheckAddress := 0x0068667C
	LoadingGameCheckAddress := 0x00695662	
	LoadingFromFreshStartUpAddress := 0x006DCDC0
}
else if VersionOffset = -0x2FF8 ; Japanese
{
	StartingNewGameCheckAddress := 0x0068467C
	LoadingGameCheckAddress := 0x00693662	
	LoadingFromFreshStartUpAddress := 0x006DADC0
}
else 
{
	StartingNewGameCheckAddress := 0x0068767C
	LoadingGameCheckAddress := 0x0069665A
	if VersionOffset = 8 ; Version 1.1
		LoadingFromFreshStartUpAddress := 0x006DDE18
	else
		LoadingFromFreshStartUpAddress := 0x006DDE28	
}
```

**Comment by Lighnat0r** [comment]
All the addresses are byte, for future reference.

**Comment by pitpo** [comment]
"LoadingGameCheckAddress" from chaos% worked. Every other address returned huge values and didn't change on load/start.

Here is the pull request with fix #4

**Comment by Lighnat0r** [comment]
The reason all other addresses 'returned huge values' is that, like I said, they're byte addresses. Reading them as dword addresses is obviously not going to work.

"LoadingGameCheckAddress" from chaos% is, as commented in the code, the only dword address.

**Comment by zoton2** [comment]
OK, I "merged" the new code in because the memory address found seems to work in most cases.

The only time it will no longer reset is if your timer is running and you start the game fresh, and then start a new game. This can actually be useful in certain places, so I think we plan to leave it like that.

**Comment by pitpo** [comment]
Now that I think about it... What is the point of this check ```vars.gameState.Old != 12```?
Apparently ``` vars.gameState.Old == 13 ``` works just fine and with this, that additional check isn't required.

**Comment by zoton2** [comment]
Yeah, that ```vars.gameState.Old != 12``` was there so it could reset after booting the game up again, so I guess we could replace that with ```vars.gameState.Old == 13``` and remove the new memory adress.

I'll have to look at the current time thing, but that's probably not hard either.
