### ISSUE TITLE
gta3: move new asl to releases and rename, make changes accordingly in livesplit xml aswell

### ISSUE THREAD

**Issue by iguaan** [zoton2/LiveSplit.Scripts#20]
Since it was pushed to livesplit xml, these changes should be made aswell

**Comment by zoton2** [comment]
Not sure *who* pushed it to the XML heh, needs copying to the `Releases` folder yeah and making sure it's actually in a stable state (but apparently it is, I just didn't fully check it and finish it for some reason).

**Comment by iguaan** [comment]
I was opposed to the idea, but the PR was made and it was merged.
